spring.application.name=notification-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8082/eureka/
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group